import { M_PLUS_Code_Latin, Style_Script } from 'next/font/google'
import './globals.css'

const codeLatin = M_PLUS_Code_Latin({ subsets: ['latin'] })
const styleScript = Style_Script({  
  weight: '400',
  subsets: ['latin'],
})




export const metadata = {
  title: 'Jammming',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={codeLatin.className}>{children}</body>
    </html>
  )
}
